SELECT *
FROM product; -- DISPLAY ENTIRE DATA FROM PRODUCTS TABLE

SELECT ADDRESS_ID, CITY, STATE, PINCODE
FROM address; -- DISPLAY ONLY ADDRESS_ID, CIT, STATE, PINCODE COLUMNS FROM ADDRESS TABLE

SELECT DISTINCT CITY
FROM address; -- DISPLAY UNIQUES CITIES IN THE ADDRESS TABLE

DELETE
FROM product
WHERE PRODUCT_ID = 999999; -- DELETE ALL THE RECORDS FROM PRODUCTS TABLE WHOSE PRODUCT_ID IS 999999
SELECT *
FROM product;

UPDATE product
SET PRODUCT_PRICE = PRODUCT_PRICE - (PRODUCT_PRICE * 0.25);
SELECT *
FROM product; -- UPDATE THE PRICE OF ALL PRODUCTS IN THE PRODUCTS TABLE TO A 25% LESSER VALUE
-- SET SQL_SAFE_UPDATES = 0

SELECT *
FROM address
LIMIT 10 -- DISPLAY THE TOP 10 ROWS FROM ADDRESS TABLE